name: Definitions
on:
  schedule: [{ cron: "0 */6 * * *" }] # 6hrly https://crontab.guru/#0_*/6_*_*_*
  workflow_dispatch:

permissions: {}
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with: { egress-policy: audit }
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: npm ci

      - run: npm run scrape-definitions
      - run: npm run lint:lts -- --fix
        continue-on-error: true
      - run: npm run commit-definitions
        env:
          GIT_AUTHOR_NAME: ${{ vars.NODENV_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.NODENV_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GHA_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GHA_BOT_EMAIL }}

      - run: git log --format='- %s' --reverse ${{github.sha}}.. >> ${{ runner.temp }}/pr-body
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: latest-scraped-definitions
          title: "Scraped latest definitions"
          body-path: ${{ runner.temp }}/pr-body

  lts:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with: { egress-policy: audit }
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: npm ci

      - run: npm run lint:lts -- --fix

      - if: failure()
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
          committer: "nodenv bot <jason.karns+nodenv@github.com>"
          commit-message: "Add LTS warning messages"
          branch: lts-warning-message
          title: "Adds/Updates LTS warning messages"
          body: |-
            [![node lts schedule](https://raw.githubusercontent.com/nodejs/Release/main/schedule.svg)](https://github.com/nodejs/Release)

            > Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
