name: Fix LTS Warnings
on:
  schedule: [{ cron:  '0 0 * * *' }] # daily: https://crontab.guru/#0_0_*_*_*
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint:lts -- --fix
    - if: failure()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.BOT_TOKEN }}
        committer: 'nodenv bot <jason.karns+nodenv@github.com>'
        commit-message: 'Add LTS warning messages'
        branch: lts-warning-message
        title: 'Adds/Updates LTS warning messages'
        body: |-
          [![node lts schedule](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg)](https://github.com/nodejs/Release)

          > Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
