name: Lint Checksums
on:
  pull_request:
    paths: 'share/node-build/**'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run lint:checksums -- origin/${{github.base_ref}}
